CREATE TABLE PERSON (
   id INT AUTO_INCREMENT NOT NULL,
   name VARCHAR(50) NOT NULL,
   PRIMARY KEY (ID)
);

CREATE TABLE PROPERTY (
   id INT AUTO_INCREMENT NOT NULL,
   name VARCHAR(50) NOT NULL,
   owner_id INT NOT NULL,
   PRIMARY KEY (ID)
);

ALTER TABLE PROPERTY
    ADD FOREIGN KEY (owner_id)
        REFERENCES PERSON(id);

CREATE TABLE BOOKING (
   id INT AUTO_INCREMENT NOT NULL,
   start_date TIMESTAMP NOT NULL,
   end_date TIMESTAMP NOT NULL,
   person_id INT NOT NULL,
   property_id INT NOT NULL,
   PRIMARY KEY (ID)
);

ALTER TABLE BOOKING
    ADD FOREIGN KEY (person_id)
        REFERENCES PERSON(id);

ALTER TABLE BOOKING
    ADD FOREIGN KEY (property_id)
        REFERENCES PROPERTY(id);

INSERT INTO PERSON (name) VALUES ('GUEST');
INSERT INTO PERSON (name) VALUES ('OWNER');

INSERT INTO PROPERTY (name, owner_id) VALUES ('OWNER HOUSE 1', 2);
INSERT INTO PROPERTY (name, owner_id) VALUES ('OWNER HOUSE 2', 2);
INSERT INTO PROPERTY (name, owner_id) VALUES ('OWNER HOUSE 3', 2);

INSERT INTO BOOKING (start_date, end_date, person_id, property_id) VALUES ('2023-07-01', '2023-07-31',1,1);